name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@master
      with:
        args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
    
